export const DiagnosticCode = {
  UnexpectedCharacter: "PLN001",
  UnterminatedString: "PLN002",
  MalformedLiteralOrEscape: "PLN003",
  UnterminatedInterpolation: "PLN004",
  InvalidInterpolation: "PLN005",
  ExpectedTypeSyntax: "PLN010",
  ExpectedExpression: "PLN011",
  ParseExpectedToken: "PLN012",
  DuplicateName: "PLN100",
  DuplicateParameter: "PLN101",
  UnknownName: "PLN102",
  CannotCallNonFunction: "PLN200",
  WrongArgumentCount: "PLN201",
  TypeMismatch: "PLN202",
  MissingReturn: "PLN203",
  IncompatibleOperands: "PLN204",
  MissingIfElseValue: "PLN205",
  CannotAssign: "PLN206",
  BreakOutsideLoop: "PLN207",
  ContinueOutsideLoop: "PLN208",
  MissingBreakValue: "PLN209",
  BreakValueInStatementLoop: "PLN210",
  MissingWhileElseValue: "PLN211",
  CannotInferArrayElementType: "PLN212",
  CannotIndexNonArray: "PLN213",
  UnknownProperty: "PLN214",
} as const;
