export { check } from "./checker";
export { generateJavaScript } from "./codegen";
export { analyze, compile, lex, parse } from "./compiler";
export { renderDiagnostic, renderDiagnostics } from "./diagnostic-renderer";
export { findHoverTarget, findNodeAt } from "./query";
export { formatType } from "./types";
export type { NodeId, Program } from "./ast";
export type { AnalyzeResult, CompileResult, Diagnostic } from "./compiler";
export type { RenderDiagnosticOptions } from "./diagnostic-renderer";
export type { Definition, ReferenceTarget, Semantics } from "./semantics";
export type { HoverTarget, HoverTargetKind } from "./query";
export type { Span, SourceLocation } from "./span";
