import type { Span } from "./span";

export type TokenKind =
  | "Identifier"
  | "Number"
  | "BigInt"
  | "String"
  | "MultilineString"
  | "DocComment"
  | "ModuleDocComment"
  | "Import"
  | "Export"
  | "As"
  | "Const"
  | "Let"
  | "Type"
  | "Fn"
  | "Enum"
  | "Match"
  | "Return"
  | "If"
  | "Else"
  | "While"
  | "Break"
  | "Continue"
  | "True"
  | "False"
  | "And"
  | "Or"
  | "NumberType"
  | "BigIntType"
  | "StringType"
  | "BooleanType"
  | "VoidType"
  | "LeftParen"
  | "RightParen"
  | "LeftBrace"
  | "RightBrace"
  | "LeftBracket"
  | "RightBracket"
  | "At"
  | "Dot"
  | "Comma"
  | "Colon"
  | "Semicolon"
  | "Equal"
  | "Arrow"
  | "Plus"
  | "PlusPlus"
  | "PlusEqual"
  | "Minus"
  | "MinusEqual"
  | "Star"
  | "StarEqual"
  | "Slash"
  | "SlashEqual"
  | "Percent"
  | "PercentEqual"
  | "Bang"
  | "EqualEqual"
  | "BangEqual"
  | "Greater"
  | "GreaterEqual"
  | "Less"
  | "LessEqual"
  | "Eof"
  | "Invalid";

export type Token = {
  readonly kind: TokenKind;
  readonly text: string;
  readonly span: Span;
};
